/* Generated By:JJTree&JavaCC: Do not edit this line. Parser.java */
  package org.merka.mobilelisf.interpreter;
  import org.merka.mobilelisf.interpreter.ast.*;
import org.merka.mobilelisf.interpreter.visitor.*;


public class Parser/*@bgen(jjtree)*/implements ParserTreeConstants, ParserConstants {/*@bgen(jjtree)*/
  protected static JJTParserState jjtree = new JJTParserState();

  static final public ASTProgramma Programma() throws ParseException {
 /*@bgen(jjtree) Programma */
  ASTProgramma jjtn000 = new ASTProgramma(JJTPROGRAMMA);
  boolean jjtc000 = true;
  jjtree.openNodeScope(jjtn000);
    try {
      Comando();
      jj_consume_token(4);
      label_1:
      while (true) {
        switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
        case 10:
        case 11:
        case 12:
        case 13:
        case 14:
        case VARLITERAL:
          ;
          break;
        default:
          jj_la1[0] = jj_gen;
          break label_1;
        }
        Comando();
        jj_consume_token(4);
      }
      jj_consume_token(0);
          jjtree.closeNodeScope(jjtn000, true);
          jjtc000 = false;
            {if (true) return jjtn000;}
    } catch (Throwable jjte000) {
      if (jjtc000) {
        jjtree.clearNodeScope(jjtn000);
        jjtc000 = false;
      } else {
        jjtree.popNode();
      }
      if (jjte000 instanceof RuntimeException) {
        {if (true) throw (RuntimeException)jjte000;}
      }
      if (jjte000 instanceof ParseException) {
        {if (true) throw (ParseException)jjte000;}
      }
      {if (true) throw (Error)jjte000;}
    } finally {
      if (jjtc000) {
        jjtree.closeNodeScope(jjtn000, true);
      }
    }
    throw new Error("Missing return statement in function");
  }

  static final public void Comando() throws ParseException {
    Token sgn = null;
    if (jj_2_1(2)) {
                     ASTComandoAssegnamento jjtn001 = new ASTComandoAssegnamento(JJTCOMANDOASSEGNAMENTO);
                     boolean jjtc001 = true;
                     jjtree.openNodeScope(jjtn001);
      try {
        Variabile();
        jj_consume_token(5);
        Funzione();
      } catch (Throwable jjte001) {
                     if (jjtc001) {
                       jjtree.clearNodeScope(jjtn001);
                       jjtc001 = false;
                     } else {
                       jjtree.popNode();
                     }
                     if (jjte001 instanceof RuntimeException) {
                       {if (true) throw (RuntimeException)jjte001;}
                     }
                     if (jjte001 instanceof ParseException) {
                       {if (true) throw (ParseException)jjte001;}
                     }
                     {if (true) throw (Error)jjte001;}
      } finally {
                     if (jjtc001) {
                       jjtree.closeNodeScope(jjtn001, true);
                     }
      }
    } else if (jj_2_2(2)) {
                     ASTComandoCalcolo jjtn002 = new ASTComandoCalcolo(JJTCOMANDOCALCOLO);
                     boolean jjtc002 = true;
                     jjtree.openNodeScope(jjtn002);
      try {
        Variabile();
        jj_consume_token(6);
        switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
        case 7:
          sgn = jj_consume_token(7);
          break;
        default:
          jj_la1[1] = jj_gen;
          ;
        }
        Num();
                                                    if(sgn != null)
                                                    {
                                                        ASTNum num = (ASTNum)jjtree.peekNode();
                                                        num.setValue(- num.getValue());
                                                    }
        jj_consume_token(8);
      } catch (Throwable jjte002) {
                     if (jjtc002) {
                       jjtree.clearNodeScope(jjtn002);
                       jjtc002 = false;
                     } else {
                       jjtree.popNode();
                     }
                     if (jjte002 instanceof RuntimeException) {
                       {if (true) throw (RuntimeException)jjte002;}
                     }
                     if (jjte002 instanceof ParseException) {
                       {if (true) throw (ParseException)jjte002;}
                     }
                     {if (true) throw (Error)jjte002;}
      } finally {
                     if (jjtc002) {
                       jjtree.closeNodeScope(jjtn002, true);
                     }
      }
    } else {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case VARLITERAL:
        ASTComandoStampa jjtn003 = new ASTComandoStampa(JJTCOMANDOSTAMPA);
        boolean jjtc003 = true;
        jjtree.openNodeScope(jjtn003);
        try {
          Variabile();
          jj_consume_token(9);
        } catch (Throwable jjte003) {
        if (jjtc003) {
          jjtree.clearNodeScope(jjtn003);
          jjtc003 = false;
        } else {
          jjtree.popNode();
        }
        if (jjte003 instanceof RuntimeException) {
          {if (true) throw (RuntimeException)jjte003;}
        }
        if (jjte003 instanceof ParseException) {
          {if (true) throw (ParseException)jjte003;}
        }
        {if (true) throw (Error)jjte003;}
        } finally {
        if (jjtc003) {
          jjtree.closeNodeScope(jjtn003, true);
        }
        }
        break;
      case 10:
        ASTComandoAlbero jjtn004 = new ASTComandoAlbero(JJTCOMANDOALBERO);
        boolean jjtc004 = true;
        jjtree.openNodeScope(jjtn004);
        try {
          jj_consume_token(10);
          Variabile();
        } catch (Throwable jjte004) {
        if (jjtc004) {
          jjtree.clearNodeScope(jjtn004);
          jjtc004 = false;
        } else {
          jjtree.popNode();
        }
        if (jjte004 instanceof RuntimeException) {
          {if (true) throw (RuntimeException)jjte004;}
        }
        if (jjte004 instanceof ParseException) {
          {if (true) throw (ParseException)jjte004;}
        }
        {if (true) throw (Error)jjte004;}
        } finally {
        if (jjtc004) {
          jjtree.closeNodeScope(jjtn004, true);
        }
        }
        break;
      case 11:
        ASTComandoElenco jjtn005 = new ASTComandoElenco(JJTCOMANDOELENCO);
        boolean jjtc005 = true;
        jjtree.openNodeScope(jjtn005);
        try {
          jj_consume_token(11);
        } finally {
        if (jjtc005) {
          jjtree.closeNodeScope(jjtn005, true);
        }
        }
        break;
      case 12:
        ASTComandoCancellaVariabile jjtn006 = new ASTComandoCancellaVariabile(JJTCOMANDOCANCELLAVARIABILE);
        boolean jjtc006 = true;
        jjtree.openNodeScope(jjtn006);
        try {
          jj_consume_token(12);
          Variabile();
        } catch (Throwable jjte006) {
        if (jjtc006) {
          jjtree.clearNodeScope(jjtn006);
          jjtc006 = false;
        } else {
          jjtree.popNode();
        }
        if (jjte006 instanceof RuntimeException) {
          {if (true) throw (RuntimeException)jjte006;}
        }
        if (jjte006 instanceof ParseException) {
          {if (true) throw (ParseException)jjte006;}
        }
        {if (true) throw (Error)jjte006;}
        } finally {
        if (jjtc006) {
          jjtree.closeNodeScope(jjtn006, true);
        }
        }
        break;
      case 13:
        ASTComandoCancellaTutto jjtn007 = new ASTComandoCancellaTutto(JJTCOMANDOCANCELLATUTTO);
        boolean jjtc007 = true;
        jjtree.openNodeScope(jjtn007);
        try {
          jj_consume_token(13);
        } finally {
        if (jjtc007) {
          jjtree.closeNodeScope(jjtn007, true);
        }
        }
        break;
      case 14:
        ASTComandoDisegno jjtn008 = new ASTComandoDisegno(JJTCOMANDODISEGNO);
        boolean jjtc008 = true;
        jjtree.openNodeScope(jjtn008);
        try {
          jj_consume_token(14);
          Variabile();
        } catch (Throwable jjte008) {
        if (jjtc008) {
          jjtree.clearNodeScope(jjtn008);
          jjtc008 = false;
        } else {
          jjtree.popNode();
        }
        if (jjte008 instanceof RuntimeException) {
          {if (true) throw (RuntimeException)jjte008;}
        }
        if (jjte008 instanceof ParseException) {
          {if (true) throw (ParseException)jjte008;}
        }
        {if (true) throw (Error)jjte008;}
        } finally {
        if (jjtc008) {
          jjtree.closeNodeScope(jjtn008, true);
        }
        }
        break;
      default:
        jj_la1[2] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
    }
  }

  static final public void Funzione() throws ParseException {
    Termine();
    label_2:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case 7:
      case 15:
        ;
        break;
      default:
        jj_la1[3] = jj_gen;
        break label_2;
      }
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case 15:
        jj_consume_token(15);
                     ASTSomma jjtn001 = new ASTSomma(JJTSOMMA);
                     boolean jjtc001 = true;
                     jjtree.openNodeScope(jjtn001);
        try {
          Termine();
        } catch (Throwable jjte001) {
                     if (jjtc001) {
                       jjtree.clearNodeScope(jjtn001);
                       jjtc001 = false;
                     } else {
                       jjtree.popNode();
                     }
                     if (jjte001 instanceof RuntimeException) {
                       {if (true) throw (RuntimeException)jjte001;}
                     }
                     if (jjte001 instanceof ParseException) {
                       {if (true) throw (ParseException)jjte001;}
                     }
                     {if (true) throw (Error)jjte001;}
        } finally {
                     if (jjtc001) {
                       jjtree.closeNodeScope(jjtn001,  2);
                     }
        }
        break;
      case 7:
        jj_consume_token(7);
                                               ASTDifferenza jjtn002 = new ASTDifferenza(JJTDIFFERENZA);
                                               boolean jjtc002 = true;
                                               jjtree.openNodeScope(jjtn002);
        try {
          Termine();
        } catch (Throwable jjte002) {
                                               if (jjtc002) {
                                                 jjtree.clearNodeScope(jjtn002);
                                                 jjtc002 = false;
                                               } else {
                                                 jjtree.popNode();
                                               }
                                               if (jjte002 instanceof RuntimeException) {
                                                 {if (true) throw (RuntimeException)jjte002;}
                                               }
                                               if (jjte002 instanceof ParseException) {
                                                 {if (true) throw (ParseException)jjte002;}
                                               }
                                               {if (true) throw (Error)jjte002;}
        } finally {
                                               if (jjtc002) {
                                                 jjtree.closeNodeScope(jjtn002,  2);
                                               }
        }
        break;
      default:
        jj_la1[4] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
    }
  }

  static final public void Termine() throws ParseException {
    Monomio();
    label_3:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case 16:
      case 17:
        ;
        break;
      default:
        jj_la1[5] = jj_gen;
        break label_3;
      }
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case 16:
        jj_consume_token(16);
                      ASTProdotto jjtn001 = new ASTProdotto(JJTPRODOTTO);
                      boolean jjtc001 = true;
                      jjtree.openNodeScope(jjtn001);
        try {
          Monomio();
        } catch (Throwable jjte001) {
                      if (jjtc001) {
                        jjtree.clearNodeScope(jjtn001);
                        jjtc001 = false;
                      } else {
                        jjtree.popNode();
                      }
                      if (jjte001 instanceof RuntimeException) {
                        {if (true) throw (RuntimeException)jjte001;}
                      }
                      if (jjte001 instanceof ParseException) {
                        {if (true) throw (ParseException)jjte001;}
                      }
                      {if (true) throw (Error)jjte001;}
        } finally {
                      if (jjtc001) {
                        jjtree.closeNodeScope(jjtn001,  2);
                      }
        }
        break;
      case 17:
        jj_consume_token(17);
                                                   ASTDivisione jjtn002 = new ASTDivisione(JJTDIVISIONE);
                                                   boolean jjtc002 = true;
                                                   jjtree.openNodeScope(jjtn002);
        try {
          Monomio();
        } catch (Throwable jjte002) {
                                                   if (jjtc002) {
                                                     jjtree.clearNodeScope(jjtn002);
                                                     jjtc002 = false;
                                                   } else {
                                                     jjtree.popNode();
                                                   }
                                                   if (jjte002 instanceof RuntimeException) {
                                                     {if (true) throw (RuntimeException)jjte002;}
                                                   }
                                                   if (jjte002 instanceof ParseException) {
                                                     {if (true) throw (ParseException)jjte002;}
                                                   }
                                                   {if (true) throw (Error)jjte002;}
        } finally {
                                                   if (jjtc002) {
                                                     jjtree.closeNodeScope(jjtn002,  2);
                                                   }
        }
        break;
      default:
        jj_la1[6] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
    }
  }

    /*
     *  questa parte di grammatica (Monomio) viene modificata:
     *  il simbolo "^" deve essere trattato come un operatore binario, associativo a sinistra
     *  e con maggiore priorità
    */
/*
void Monomio() #void:
{
    Node n, esp;
}
{*/
    /*Qui dà un warning, cmq il parser funziona correttamente (stessa situazione del "dangling else")*/
    /*l'esponente viene automaticamente associato all'espansione più interna*/
  /*
    MonomioSemplice() {n = jjtree.popNode();}
                      [Esponente() 
                        {
                         esp = jjtree.popNode();
                         ASTMonomio monomioConEsp = new ASTMonomio(ParserTreeConstants.JJTMONOMIO);
                         monomioConEsp.jjtAddChild(n,0);
                         monomioConEsp.jjtAddChild(esp,1);
                         n = monomioConEsp;
                        }
                      ] 
                      {jjtree.pushNode(n);} #Monomio(false)
}*/


/*
 *  segue la nuova grammatica 
 *  per la produzione di Monomio (Molto più semplice, non è vero?)
 *  Monomio -> MonomioSemplice ("^" MonomioSemplice)*
*/
  static final public void Monomio() throws ParseException {
    MonomioSemplice();
    label_4:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case 18:
        ;
        break;
      default:
        jj_la1[7] = jj_gen;
        break label_4;
      }
      jj_consume_token(18);
                              ASTMonomio jjtn001 = new ASTMonomio(JJTMONOMIO);
                              boolean jjtc001 = true;
                              jjtree.openNodeScope(jjtn001);
      try {
        MonomioSemplice();
      } catch (Throwable jjte001) {
                              if (jjtc001) {
                                jjtree.clearNodeScope(jjtn001);
                                jjtc001 = false;
                              } else {
                                jjtree.popNode();
                              }
                              if (jjte001 instanceof RuntimeException) {
                                {if (true) throw (RuntimeException)jjte001;}
                              }
                              if (jjte001 instanceof ParseException) {
                                {if (true) throw (ParseException)jjte001;}
                              }
                              {if (true) throw (Error)jjte001;}
      } finally {
                              if (jjtc001) {
                                jjtree.closeNodeScope(jjtn001,  2);
                              }
      }
    }
  }

  static final public void MonomioSemplice() throws ParseException {
    Node var;
    Node arg = null;
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case INTERO:
      Num();
      break;
    case VARLITERAL:
      Variabile();
         var = jjtree.popNode();
      jj_consume_token(6);
      Funzione();
      jj_consume_token(19);
                        arg = jjtree.popNode();
            if (arg != null)
            var.jjtAddChild(arg,0);
            jjtree.pushNode(var);
      break;
    case VARINDIPLITERAL:
      VariabileIndipendente();
      break;
    case 20:
    case 21:
      Seno();
      break;
    case 22:
      Coseno();
      break;
    case 23:
    case 24:
      Tangente();
      break;
    case 25:
    case 26:
      Cotangente();
      break;
    case 27:
    case 28:
      ArcoSeno();
      break;
    case 29:
      ArcoCoseno();
      break;
    case 30:
    case 31:
      ArcoTangente();
      break;
    case 32:
    case 33:
      ArcoCotangente();
      break;
    case 7:
      MonomioNegativo();
      break;
    case 34:
      LogaritmoNaturale();
      break;
    case 35:
      Logaritmo();
      break;
    case 38:
      ValoreAssoluto();
      break;
    case 39:
      Esponenziale();
      break;
    case 40:
      Fattoriale();
      break;
    case 41:
      Radice();
      break;
    case 6:
      jj_consume_token(6);
      Funzione();
      jj_consume_token(19);
      break;
    default:
      jj_la1[8] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
  }

  static final public void Num() throws ParseException {
 /*@bgen(jjtree) Num */
    ASTNum jjtn000 = new ASTNum(JJTNUM);
    boolean jjtc000 = true;
    jjtree.openNodeScope(jjtn000);Token parteInt = null;
    Token parteFraz = null;
    double value;
    try {
      parteInt = jj_consume_token(INTERO);
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case PARTEFRAZ:
        parteFraz = jj_consume_token(PARTEFRAZ);
        break;
      default:
        jj_la1[9] = jj_gen;
        ;
      }
          jjtree.closeNodeScope(jjtn000, true);
          jjtc000 = false;
            if (parteFraz == null)
                value = Double.parseDouble(parteInt.image);
            else
                value = Double.parseDouble(parteInt.image+parteFraz.image);
            jjtn000.setValue(value);
    } finally {
      if (jjtc000) {
        jjtree.closeNodeScope(jjtn000, true);
      }
    }
  }

  static final public void Seno() throws ParseException {
 /*@bgen(jjtree) Seno */
  ASTSeno jjtn000 = new ASTSeno(JJTSENO);
  boolean jjtc000 = true;
  jjtree.openNodeScope(jjtn000);
    try {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case 20:
        jj_consume_token(20);
        break;
      case 21:
        jj_consume_token(21);
        break;
      default:
        jj_la1[10] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
      Monomio();
    } catch (Throwable jjte000) {
      if (jjtc000) {
        jjtree.clearNodeScope(jjtn000);
        jjtc000 = false;
      } else {
        jjtree.popNode();
      }
      if (jjte000 instanceof RuntimeException) {
        {if (true) throw (RuntimeException)jjte000;}
      }
      if (jjte000 instanceof ParseException) {
        {if (true) throw (ParseException)jjte000;}
      }
      {if (true) throw (Error)jjte000;}
    } finally {
      if (jjtc000) {
        jjtree.closeNodeScope(jjtn000, true);
      }
    }
  }

  static final public void Coseno() throws ParseException {
 /*@bgen(jjtree) Coseno */
  ASTCoseno jjtn000 = new ASTCoseno(JJTCOSENO);
  boolean jjtc000 = true;
  jjtree.openNodeScope(jjtn000);
    try {
      jj_consume_token(22);
      Monomio();
    } catch (Throwable jjte000) {
      if (jjtc000) {
        jjtree.clearNodeScope(jjtn000);
        jjtc000 = false;
      } else {
        jjtree.popNode();
      }
      if (jjte000 instanceof RuntimeException) {
        {if (true) throw (RuntimeException)jjte000;}
      }
      if (jjte000 instanceof ParseException) {
        {if (true) throw (ParseException)jjte000;}
      }
      {if (true) throw (Error)jjte000;}
    } finally {
      if (jjtc000) {
        jjtree.closeNodeScope(jjtn000, true);
      }
    }
  }

  static final public void Tangente() throws ParseException {
 /*@bgen(jjtree) Tangente */
  ASTTangente jjtn000 = new ASTTangente(JJTTANGENTE);
  boolean jjtc000 = true;
  jjtree.openNodeScope(jjtn000);
    try {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case 23:
        jj_consume_token(23);
        break;
      case 24:
        jj_consume_token(24);
        break;
      default:
        jj_la1[11] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
      Monomio();
    } catch (Throwable jjte000) {
      if (jjtc000) {
        jjtree.clearNodeScope(jjtn000);
        jjtc000 = false;
      } else {
        jjtree.popNode();
      }
      if (jjte000 instanceof RuntimeException) {
        {if (true) throw (RuntimeException)jjte000;}
      }
      if (jjte000 instanceof ParseException) {
        {if (true) throw (ParseException)jjte000;}
      }
      {if (true) throw (Error)jjte000;}
    } finally {
      if (jjtc000) {
        jjtree.closeNodeScope(jjtn000, true);
      }
    }
  }

  static final public void Cotangente() throws ParseException {
 /*@bgen(jjtree) Cotangente */
  ASTCotangente jjtn000 = new ASTCotangente(JJTCOTANGENTE);
  boolean jjtc000 = true;
  jjtree.openNodeScope(jjtn000);
    try {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case 25:
        jj_consume_token(25);
        break;
      case 26:
        jj_consume_token(26);
        break;
      default:
        jj_la1[12] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
      Monomio();
    } catch (Throwable jjte000) {
      if (jjtc000) {
        jjtree.clearNodeScope(jjtn000);
        jjtc000 = false;
      } else {
        jjtree.popNode();
      }
      if (jjte000 instanceof RuntimeException) {
        {if (true) throw (RuntimeException)jjte000;}
      }
      if (jjte000 instanceof ParseException) {
        {if (true) throw (ParseException)jjte000;}
      }
      {if (true) throw (Error)jjte000;}
    } finally {
      if (jjtc000) {
        jjtree.closeNodeScope(jjtn000, true);
      }
    }
  }

  static final public void ArcoSeno() throws ParseException {
 /*@bgen(jjtree) ArcoSeno */
  ASTArcoSeno jjtn000 = new ASTArcoSeno(JJTARCOSENO);
  boolean jjtc000 = true;
  jjtree.openNodeScope(jjtn000);
    try {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case 27:
        jj_consume_token(27);
        break;
      case 28:
        jj_consume_token(28);
        break;
      default:
        jj_la1[13] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
      Monomio();
    } catch (Throwable jjte000) {
      if (jjtc000) {
        jjtree.clearNodeScope(jjtn000);
        jjtc000 = false;
      } else {
        jjtree.popNode();
      }
      if (jjte000 instanceof RuntimeException) {
        {if (true) throw (RuntimeException)jjte000;}
      }
      if (jjte000 instanceof ParseException) {
        {if (true) throw (ParseException)jjte000;}
      }
      {if (true) throw (Error)jjte000;}
    } finally {
      if (jjtc000) {
        jjtree.closeNodeScope(jjtn000, true);
      }
    }
  }

  static final public void ArcoCoseno() throws ParseException {
 /*@bgen(jjtree) ArcoCoseno */
  ASTArcoCoseno jjtn000 = new ASTArcoCoseno(JJTARCOCOSENO);
  boolean jjtc000 = true;
  jjtree.openNodeScope(jjtn000);
    try {
      jj_consume_token(29);
      Monomio();
    } catch (Throwable jjte000) {
      if (jjtc000) {
        jjtree.clearNodeScope(jjtn000);
        jjtc000 = false;
      } else {
        jjtree.popNode();
      }
      if (jjte000 instanceof RuntimeException) {
        {if (true) throw (RuntimeException)jjte000;}
      }
      if (jjte000 instanceof ParseException) {
        {if (true) throw (ParseException)jjte000;}
      }
      {if (true) throw (Error)jjte000;}
    } finally {
      if (jjtc000) {
        jjtree.closeNodeScope(jjtn000, true);
      }
    }
  }

  static final public void ArcoTangente() throws ParseException {
 /*@bgen(jjtree) ArcoTangente */
  ASTArcoTangente jjtn000 = new ASTArcoTangente(JJTARCOTANGENTE);
  boolean jjtc000 = true;
  jjtree.openNodeScope(jjtn000);
    try {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case 30:
        jj_consume_token(30);
        break;
      case 31:
        jj_consume_token(31);
        break;
      default:
        jj_la1[14] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
      Monomio();
    } catch (Throwable jjte000) {
      if (jjtc000) {
        jjtree.clearNodeScope(jjtn000);
        jjtc000 = false;
      } else {
        jjtree.popNode();
      }
      if (jjte000 instanceof RuntimeException) {
        {if (true) throw (RuntimeException)jjte000;}
      }
      if (jjte000 instanceof ParseException) {
        {if (true) throw (ParseException)jjte000;}
      }
      {if (true) throw (Error)jjte000;}
    } finally {
      if (jjtc000) {
        jjtree.closeNodeScope(jjtn000, true);
      }
    }
  }

  static final public void ArcoCotangente() throws ParseException {
 /*@bgen(jjtree) ArcoCotangente */
  ASTArcoCotangente jjtn000 = new ASTArcoCotangente(JJTARCOCOTANGENTE);
  boolean jjtc000 = true;
  jjtree.openNodeScope(jjtn000);
    try {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case 32:
        jj_consume_token(32);
        break;
      case 33:
        jj_consume_token(33);
        break;
      default:
        jj_la1[15] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
      Monomio();
    } catch (Throwable jjte000) {
      if (jjtc000) {
        jjtree.clearNodeScope(jjtn000);
        jjtc000 = false;
      } else {
        jjtree.popNode();
      }
      if (jjte000 instanceof RuntimeException) {
        {if (true) throw (RuntimeException)jjte000;}
      }
      if (jjte000 instanceof ParseException) {
        {if (true) throw (ParseException)jjte000;}
      }
      {if (true) throw (Error)jjte000;}
    } finally {
      if (jjtc000) {
        jjtree.closeNodeScope(jjtn000, true);
      }
    }
  }

  static final public void MonomioNegativo() throws ParseException {
 /*@bgen(jjtree) MonomioNegativo */
  ASTMonomioNegativo jjtn000 = new ASTMonomioNegativo(JJTMONOMIONEGATIVO);
  boolean jjtc000 = true;
  jjtree.openNodeScope(jjtn000);
    try {
      jj_consume_token(7);
      Monomio();
    } catch (Throwable jjte000) {
      if (jjtc000) {
        jjtree.clearNodeScope(jjtn000);
        jjtc000 = false;
      } else {
        jjtree.popNode();
      }
      if (jjte000 instanceof RuntimeException) {
        {if (true) throw (RuntimeException)jjte000;}
      }
      if (jjte000 instanceof ParseException) {
        {if (true) throw (ParseException)jjte000;}
      }
      {if (true) throw (Error)jjte000;}
    } finally {
      if (jjtc000) {
        jjtree.closeNodeScope(jjtn000, true);
      }
    }
  }

  static final public void LogaritmoNaturale() throws ParseException {
 /*@bgen(jjtree) LogaritmoNaturale */
  ASTLogaritmoNaturale jjtn000 = new ASTLogaritmoNaturale(JJTLOGARITMONATURALE);
  boolean jjtc000 = true;
  jjtree.openNodeScope(jjtn000);
    try {
      jj_consume_token(34);
      Monomio();
    } catch (Throwable jjte000) {
      if (jjtc000) {
        jjtree.clearNodeScope(jjtn000);
        jjtc000 = false;
      } else {
        jjtree.popNode();
      }
      if (jjte000 instanceof RuntimeException) {
        {if (true) throw (RuntimeException)jjte000;}
      }
      if (jjte000 instanceof ParseException) {
        {if (true) throw (ParseException)jjte000;}
      }
      {if (true) throw (Error)jjte000;}
    } finally {
      if (jjtc000) {
        jjtree.closeNodeScope(jjtn000, true);
      }
    }
  }

/*Pendente: è meglio mettere i figli di Logaritmo nell'ordine: 1-base, 2-argomento o il contrario?
  Attualmente si adotta la prima*/
  static final public void Logaritmo() throws ParseException {
    Node n, log, arg; /*Variabile appoggio*/
    ASTNum num = null;
    jj_consume_token(35);
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case 36:
      jj_consume_token(36);
      Num();
      jj_consume_token(37);
                n = jjtree.popNode();   /*rimuovo l'eventuale Num dallo stack*/
                num = (ASTNum) n;       /*cast sicuro: n è sicuramente un ASTNum*/

      break;
    default:
      jj_la1[16] = jj_gen;
      ;
    }
    Monomio();
              ASTLogaritmo jjtn001 = new ASTLogaritmo(JJTLOGARITMO);
              boolean jjtc001 = true;
              jjtree.openNodeScope(jjtn001);
    try {
              jjtree.closeNodeScope(jjtn001,  false);
              jjtc001 = false;
                arg = jjtree.popNode(); /*rimuovo il dallo stack il sotto-albero creato dalla chiamata a Monomio()*/
                if(num == null)         /*non è stata specificata la base del logaritmo => base = 10*/
                    {
                        num = new ASTNum(ParserTreeConstants.JJTNUM);
                        num.setValue(10);
                    }
            /*Aggiungo i figli nell'ordine corretto*/
            log = new ASTLogaritmo(ParserTreeConstants.JJTLOGARITMO);
            log.jjtAddChild(num,0);
            log.jjtAddChild(arg,1);
            jjtree.pushNode(log);
    } finally {
              if (jjtc001) {
                jjtree.closeNodeScope(jjtn001,  false);
              }
    }
  }

  static final public void ValoreAssoluto() throws ParseException {
 /*@bgen(jjtree) ValoreAssoluto */
  ASTValoreAssoluto jjtn000 = new ASTValoreAssoluto(JJTVALOREASSOLUTO);
  boolean jjtc000 = true;
  jjtree.openNodeScope(jjtn000);
    try {
      jj_consume_token(38);
      Monomio();
    } catch (Throwable jjte000) {
      if (jjtc000) {
        jjtree.clearNodeScope(jjtn000);
        jjtc000 = false;
      } else {
        jjtree.popNode();
      }
      if (jjte000 instanceof RuntimeException) {
        {if (true) throw (RuntimeException)jjte000;}
      }
      if (jjte000 instanceof ParseException) {
        {if (true) throw (ParseException)jjte000;}
      }
      {if (true) throw (Error)jjte000;}
    } finally {
      if (jjtc000) {
        jjtree.closeNodeScope(jjtn000, true);
      }
    }
  }

  static final public void Esponenziale() throws ParseException {
 /*@bgen(jjtree) Esponenziale */
  ASTEsponenziale jjtn000 = new ASTEsponenziale(JJTESPONENZIALE);
  boolean jjtc000 = true;
  jjtree.openNodeScope(jjtn000);
    try {
      jj_consume_token(39);
      Monomio();
    } catch (Throwable jjte000) {
      if (jjtc000) {
        jjtree.clearNodeScope(jjtn000);
        jjtc000 = false;
      } else {
        jjtree.popNode();
      }
      if (jjte000 instanceof RuntimeException) {
        {if (true) throw (RuntimeException)jjte000;}
      }
      if (jjte000 instanceof ParseException) {
        {if (true) throw (ParseException)jjte000;}
      }
      {if (true) throw (Error)jjte000;}
    } finally {
      if (jjtc000) {
        jjtree.closeNodeScope(jjtn000, true);
      }
    }
  }

  static final public void Fattoriale() throws ParseException {
 /*@bgen(jjtree) Fattoriale */
  ASTFattoriale jjtn000 = new ASTFattoriale(JJTFATTORIALE);
  boolean jjtc000 = true;
  jjtree.openNodeScope(jjtn000);
    try {
      jj_consume_token(40);
      Monomio();
    } catch (Throwable jjte000) {
      if (jjtc000) {
        jjtree.clearNodeScope(jjtn000);
        jjtc000 = false;
      } else {
        jjtree.popNode();
      }
      if (jjte000 instanceof RuntimeException) {
        {if (true) throw (RuntimeException)jjte000;}
      }
      if (jjte000 instanceof ParseException) {
        {if (true) throw (ParseException)jjte000;}
      }
      {if (true) throw (Error)jjte000;}
    } finally {
      if (jjtc000) {
        jjtree.closeNodeScope(jjtn000, true);
      }
    }
  }

/*Una radice è matematicamente identica ad un esponente frazionario --> 
  si sceglie una rappresentazione omagenea tramite la classe ASTMonomio
  Occorre creare "a mano" il seguente sotto-albero Monomio, corrispondente ad un radice:

  \indice/arg --> arg^(1/indice)

  Monomio               --> radiceFormaEsponenziale
    Argomento           --> arg
        <sotto-albero>  
    Esponente           --> esp
        Num             --> indice
*/
  static final public void Radice() throws ParseException {
    Node arg;
    Node i = null;
    ASTNum indice = null;
    jj_consume_token(41);
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case INTERO:
      Num();
                i = jjtree.popNode();
                indice = (ASTNum)i;
                indice.setValue(1/indice.getValue());      /* Esponente = 1/indice */

      break;
    default:
      jj_la1[17] = jj_gen;
      ;
    }
    jj_consume_token(17);
    Monomio();
                        if(indice == null) /*non è stato esplicitato l'indice => radice quadrata, indice=2*/
                        {
                            indice = new ASTNum(ParserTreeConstants.JJTNUM);
                            indice.setValue(0.5);
                        }
                        arg = jjtree.popNode();
                        ASTMonomio radiceFormaEsponenziale = new ASTMonomio(ParserTreeConstants.JJTMONOMIO);
                        radiceFormaEsponenziale.jjtAddChild(arg,0);
                        radiceFormaEsponenziale.jjtAddChild(indice,1);
                        jjtree.pushNode(radiceFormaEsponenziale);
  }

  static final public void Variabile() throws ParseException {
 /*@bgen(jjtree) Variabile */
    ASTVariabile jjtn000 = new ASTVariabile(JJTVARIABILE);
    boolean jjtc000 = true;
    jjtree.openNodeScope(jjtn000);Token t = null;
    try {
      t = jj_consume_token(VARLITERAL);
          jjtree.closeNodeScope(jjtn000, true);
          jjtc000 = false;
            jjtn000.setName(t.image);
    } finally {
      if (jjtc000) {
        jjtree.closeNodeScope(jjtn000, true);
      }
    }
  }

  static final public void VariabileIndipendente() throws ParseException {
 /*@bgen(jjtree) VariabileIndipendente */
  ASTVariabileIndipendente jjtn000 = new ASTVariabileIndipendente(JJTVARIABILEINDIPENDENTE);
  boolean jjtc000 = true;
  jjtree.openNodeScope(jjtn000);
    try {
      jj_consume_token(VARINDIPLITERAL);
    } finally {
      if (jjtc000) {
        jjtree.closeNodeScope(jjtn000, true);
      }
    }
  }

  static final private boolean jj_2_1(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_1(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(0, xla); }
  }

  static final private boolean jj_2_2(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_2(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(1, xla); }
  }

  static final private boolean jj_3_2() {
    if (jj_3R_5()) return true;
    if (jj_scan_token(6)) return true;
    return false;
  }

  static final private boolean jj_3_1() {
    if (jj_3R_5()) return true;
    if (jj_scan_token(5)) return true;
    return false;
  }

  static final private boolean jj_3R_5() {
    if (jj_scan_token(VARLITERAL)) return true;
    return false;
  }

  static private boolean jj_initialized_once = false;
  static public ParserTokenManager token_source;
  static SimpleCharStream jj_input_stream;
  static public Token token, jj_nt;
  static private int jj_ntk;
  static private Token jj_scanpos, jj_lastpos;
  static private int jj_la;
  static public boolean lookingAhead = false;
  static private boolean jj_semLA;
  static private int jj_gen;
  static final private int[] jj_la1 = new int[18];
  static private int[] jj_la1_0;
  static private int[] jj_la1_1;
  static {
      jj_la1_0();
      jj_la1_1();
   }
   private static void jj_la1_0() {
      jj_la1_0 = new int[] {0x7c00,0x80,0x7c00,0x8080,0x8080,0x30000,0x30000,0x40000,0xfff000c0,0x0,0x300000,0x1800000,0x6000000,0x18000000,0xc0000000,0x0,0x0,0x0,};
   }
   private static void jj_la1_1() {
      jj_la1_1 = new int[] {0x1000,0x0,0x1000,0x0,0x0,0x0,0x0,0x0,0x37cf,0x800,0x0,0x0,0x0,0x0,0x0,0x3,0x10,0x400,};
   }
  static final private JJCalls[] jj_2_rtns = new JJCalls[2];
  static private boolean jj_rescan = false;
  static private int jj_gc = 0;

  public Parser(java.io.InputStream stream) {
    if (jj_initialized_once) {
      System.out.println("ERROR: Second call to constructor of static parser.  You must");
      System.out.println("       either use ReInit() or set the JavaCC option STATIC to false");
      System.out.println("       during parser generation.");
      throw new Error();
    }
    jj_initialized_once = true;
    jj_input_stream = new SimpleCharStream(stream, 1, 1);
    token_source = new ParserTokenManager(jj_input_stream);
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 18; i++) jj_la1[i] = -1;
    for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  static public void ReInit(java.io.InputStream stream) {
    jj_input_stream.ReInit(stream, 1, 1);
    token_source.ReInit(jj_input_stream);
    token = new Token();
    jj_ntk = -1;
    jjtree.reset();
    jj_gen = 0;
    for (int i = 0; i < 18; i++) jj_la1[i] = -1;
    for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  public Parser(java.io.Reader stream) {
    if (jj_initialized_once) {
      System.out.println("ERROR: Second call to constructor of static parser.  You must");
      System.out.println("       either use ReInit() or set the JavaCC option STATIC to false");
      System.out.println("       during parser generation.");
      throw new Error();
    }
    jj_initialized_once = true;
    jj_input_stream = new SimpleCharStream(stream, 1, 1);
    token_source = new ParserTokenManager(jj_input_stream);
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 18; i++) jj_la1[i] = -1;
    for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  static public void ReInit(java.io.Reader stream) {
    jj_input_stream.ReInit(stream, 1, 1);
    token_source.ReInit(jj_input_stream);
    token = new Token();
    jj_ntk = -1;
    jjtree.reset();
    jj_gen = 0;
    for (int i = 0; i < 18; i++) jj_la1[i] = -1;
    for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  public Parser(ParserTokenManager tm) {
    if (jj_initialized_once) {
      System.out.println("ERROR: Second call to constructor of static parser.  You must");
      System.out.println("       either use ReInit() or set the JavaCC option STATIC to false");
      System.out.println("       during parser generation.");
      throw new Error();
    }
    jj_initialized_once = true;
    token_source = tm;
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 18; i++) jj_la1[i] = -1;
    for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  public void ReInit(ParserTokenManager tm) {
    token_source = tm;
    token = new Token();
    jj_ntk = -1;
    jjtree.reset();
    jj_gen = 0;
    for (int i = 0; i < 18; i++) jj_la1[i] = -1;
    for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  static final private Token jj_consume_token(int kind) throws ParseException {
    Token oldToken;
    if ((oldToken = token).next != null) token = token.next;
    else token = token.next = token_source.getNextToken();
    jj_ntk = -1;
    if (token.kind == kind) {
      jj_gen++;
      if (++jj_gc > 100) {
        jj_gc = 0;
        for (int i = 0; i < jj_2_rtns.length; i++) {
          JJCalls c = jj_2_rtns[i];
          while (c != null) {
            if (c.gen < jj_gen) c.first = null;
            c = c.next;
          }
        }
      }
      return token;
    }
    token = oldToken;
    jj_kind = kind;
    throw generateParseException();
  }

  static private final class LookaheadSuccess extends java.lang.Error { }
  static final private LookaheadSuccess jj_ls = new LookaheadSuccess();
  static final private boolean jj_scan_token(int kind) {
    if (jj_scanpos == jj_lastpos) {
      jj_la--;
      if (jj_scanpos.next == null) {
        jj_lastpos = jj_scanpos = jj_scanpos.next = token_source.getNextToken();
      } else {
        jj_lastpos = jj_scanpos = jj_scanpos.next;
      }
    } else {
      jj_scanpos = jj_scanpos.next;
    }
    if (jj_rescan) {
      int i = 0; Token tok = token;
      while (tok != null && tok != jj_scanpos) { i++; tok = tok.next; }
      if (tok != null) jj_add_error_token(kind, i);
    }
    if (jj_scanpos.kind != kind) return true;
    if (jj_la == 0 && jj_scanpos == jj_lastpos) throw jj_ls;
    return false;
  }

  static final public Token getNextToken() {
    if (token.next != null) token = token.next;
    else token = token.next = token_source.getNextToken();
    jj_ntk = -1;
    jj_gen++;
    return token;
  }

  static final public Token getToken(int index) {
    Token t = lookingAhead ? jj_scanpos : token;
    for (int i = 0; i < index; i++) {
      if (t.next != null) t = t.next;
      else t = t.next = token_source.getNextToken();
    }
    return t;
  }

  static final private int jj_ntk() {
    if ((jj_nt=token.next) == null)
      return (jj_ntk = (token.next=token_source.getNextToken()).kind);
    else
      return (jj_ntk = jj_nt.kind);
  }

  static private java.util.Vector jj_expentries = new java.util.Vector();
  static private int[] jj_expentry;
  static private int jj_kind = -1;
  static private int[] jj_lasttokens = new int[100];
  static private int jj_endpos;

  static private void jj_add_error_token(int kind, int pos) {
    if (pos >= 100) return;
    if (pos == jj_endpos + 1) {
      jj_lasttokens[jj_endpos++] = kind;
    } else if (jj_endpos != 0) {
      jj_expentry = new int[jj_endpos];
      for (int i = 0; i < jj_endpos; i++) {
        jj_expentry[i] = jj_lasttokens[i];
      }
      boolean exists = false;
      for (java.util.Enumeration e = jj_expentries.elements(); e.hasMoreElements();) {
        int[] oldentry = (int[])(e.nextElement());
        if (oldentry.length == jj_expentry.length) {
          exists = true;
          for (int i = 0; i < jj_expentry.length; i++) {
            if (oldentry[i] != jj_expentry[i]) {
              exists = false;
              break;
            }
          }
          if (exists) break;
        }
      }
      if (!exists) jj_expentries.addElement(jj_expentry);
      if (pos != 0) jj_lasttokens[(jj_endpos = pos) - 1] = kind;
    }
  }

  static public ParseException generateParseException() {
    jj_expentries.removeAllElements();
    boolean[] la1tokens = new boolean[46];
    for (int i = 0; i < 46; i++) {
      la1tokens[i] = false;
    }
    if (jj_kind >= 0) {
      la1tokens[jj_kind] = true;
      jj_kind = -1;
    }
    for (int i = 0; i < 18; i++) {
      if (jj_la1[i] == jj_gen) {
        for (int j = 0; j < 32; j++) {
          if ((jj_la1_0[i] & (1<<j)) != 0) {
            la1tokens[j] = true;
          }
          if ((jj_la1_1[i] & (1<<j)) != 0) {
            la1tokens[32+j] = true;
          }
        }
      }
    }
    for (int i = 0; i < 46; i++) {
      if (la1tokens[i]) {
        jj_expentry = new int[1];
        jj_expentry[0] = i;
        jj_expentries.addElement(jj_expentry);
      }
    }
    jj_endpos = 0;
    jj_rescan_token();
    jj_add_error_token(0, 0);
    int[][] exptokseq = new int[jj_expentries.size()][];
    for (int i = 0; i < jj_expentries.size(); i++) {
      exptokseq[i] = (int[])jj_expentries.elementAt(i);
    }
    return new ParseException(token, exptokseq, tokenImage);
  }

  static final public void enable_tracing() {
  }

  static final public void disable_tracing() {
  }

  static final private void jj_rescan_token() {
    jj_rescan = true;
    for (int i = 0; i < 2; i++) {
      JJCalls p = jj_2_rtns[i];
      do {
        if (p.gen > jj_gen) {
          jj_la = p.arg; jj_lastpos = jj_scanpos = p.first;
          switch (i) {
            case 0: jj_3_1(); break;
            case 1: jj_3_2(); break;
          }
        }
        p = p.next;
      } while (p != null);
    }
    jj_rescan = false;
  }

  static final private void jj_save(int index, int xla) {
    JJCalls p = jj_2_rtns[index];
    while (p.gen > jj_gen) {
      if (p.next == null) { p = p.next = new JJCalls(); break; }
      p = p.next;
    }
    p.gen = jj_gen + xla - jj_la; p.first = token; p.arg = xla;
  }

  static final class JJCalls {
    int gen;
    Token first;
    int arg;
    JJCalls next;
  }

}
