/* Generated By:JJTree&JavaCC: Do not edit this line. ParserConstants.java */
package org.merka.mobilelisf.interpreter;

public interface ParserConstants {

  int EOF = 0;
  int INTERO = 42;
  int PARTEFRAZ = 43;
  int VARLITERAL = 44;
  int VARINDIPLITERAL = 45;

  int DEFAULT = 0;

  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\n\"",
    "\"\\t\"",
    "\";\"",
    "\"=\"",
    "\"(\"",
    "\"-\"",
    "\")?\"",
    "\"?\"",
    "\"tree\"",
    "\"list\"",
    "\"delete\"",
    "\"delete all\"",
    "\"draw\"",
    "\"+\"",
    "\"*\"",
    "\"/\"",
    "\"^\"",
    "\")\"",
    "\"sin\"",
    "\"sen\"",
    "\"cos\"",
    "\"tan\"",
    "\"tg\"",
    "\"cotan\"",
    "\"cotg\"",
    "\"arcsin\"",
    "\"arcsen\"",
    "\"arccos\"",
    "\"arctan\"",
    "\"arctg\"",
    "\"arccotan\"",
    "\"arccotg\"",
    "\"ln\"",
    "\"log\"",
    "\"<\"",
    "\">\"",
    "\"abs\"",
    "\"exp\"",
    "\"fact\"",
    "\"\\\\\"",
    "<INTERO>",
    "<PARTEFRAZ>",
    "<VARLITERAL>",
    "\"x\"",
  };

}
