/* Generated By:JJTree: Do not edit this line. ASTComandoElenco.java */

package org.merka.mobilelisf.interpreter.ast;
import org.merka.mobilelisf.interpreter.*;
import org.merka.mobilelisf.interpreter.visitor.*;

public class ASTComandoElenco extends SimpleNode {
  public ASTComandoElenco(int id) {
    super(id);
  }

  public ASTComandoElenco(Parser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(ParserVisitor visitor, Object data)throws Exception
  {
    return visitor.visit(this, data);
  }
  public boolean isLeaf()
  {
      return true;
  }
}
