/* Generated By:JJTree: Do not edit this line. ASTNum.java */

package org.merka.mobilelisf.interpreter.ast;
import org.merka.mobilelisf.interpreter.*;
import org.merka.mobilelisf.interpreter.visitor.*;

public class ASTNum extends SimpleNode {
    protected double value;
    
    public void setValue(double value){
        this.value = value;
    }
    
    public double getValue(){
        return this.value;
    }
    
  public ASTNum(int id) {
    super(id);
  }
  
  public ASTNum(Parser p, int id) {
    super(p, id);
  }
  
  public ASTNum(double value,int id)
  {
      this(id);
      this.value = value;
  }
  
  public String toString()
  {
      String superString = super.toString();
      return superString + "; value = "+value;
  }
  
  /** Accept the visitor. **/
  public Object jjtAccept(ParserVisitor visitor, Object data)throws Exception {
    return visitor.visit(this, data);
  }
  
  public boolean isLeaf(){
      return true;
  }
}
