/* Generated By:JJTree: Do not edit this line. ASTVariabile.java */

package org.merka.mobilelisf.interpreter.ast;
import org.merka.mobilelisf.interpreter.*;
import org.merka.mobilelisf.interpreter.visitor.*;

public class ASTVariabile extends SimpleNode {
    protected String name = null;
    
    public void setName(String name){
        this.name = name;
    }
    
    public String getName(){
        return this.name;
    }
    
  public ASTVariabile(int id) {
    super(id);
  }

  public ASTVariabile(Parser p, int id) {
    super(p, id);
  }
  
  public String toString()
  {
      String superString = super.toString();
      return superString + "; name = \"" + name + "\"";
  }

  /** Accept the visitor. **/
  public Object jjtAccept(ParserVisitor visitor, Object data)throws Exception
  {
    return visitor.visit(this, data);
  }
  
  /*Ridefinisce il metodo dell'interfaccia TreeNode*/
  public boolean isLeaf()
  {
      return this.jjtGetNumChildren() == 0;
  }
}
