/* Generated By:JJTree: Do not edit this line. ast\ParserTreeConstants.java */

package org.merka.mobilelisf.interpreter.ast;

public interface ParserTreeConstants
{
  public int JJTPROGRAMMA = 0;
  public int JJTVOID = 1;
  public int JJTCOMANDOASSEGNAMENTO = 2;
  public int JJTCOMANDOCALCOLO = 3;
  public int JJTCOMANDOSTAMPA = 4;
  public int JJTCOMANDOALBERO = 5;
  public int JJTCOMANDOELENCO = 6;
  public int JJTCOMANDOCANCELLAVARIABILE = 7;
  public int JJTCOMANDOCANCELLATUTTO = 8;
  public int JJTCOMANDODISEGNO = 9;
  public int JJTSOMMA = 10;
  public int JJTDIFFERENZA = 11;
  public int JJTPRODOTTO = 12;
  public int JJTDIVISIONE = 13;
  public int JJTMONOMIO = 14;
  public int JJTNUM = 15;
  public int JJTSENO = 16;
  public int JJTCOSENO = 17;
  public int JJTTANGENTE = 18;
  public int JJTCOTANGENTE = 19;
  public int JJTARCOSENO = 20;
  public int JJTARCOCOSENO = 21;
  public int JJTARCOTANGENTE = 22;
  public int JJTARCOCOTANGENTE = 23;
  public int JJTMONOMIONEGATIVO = 24;
  public int JJTLOGARITMONATURALE = 25;
  public int JJTLOGARITMO = 26;
  public int JJTVALOREASSOLUTO = 27;
  public int JJTESPONENZIALE = 28;
  public int JJTFATTORIALE = 29;
  public int JJTVARIABILE = 30;
  public int JJTVARIABILEINDIPENDENTE = 31;


  public String[] jjtNodeName = {
    "Programma",
    "void",
    "ComandoAssegnamento",
    "ComandoCalcolo",
    "ComandoStampa",
    "ComandoAlbero",
    "ComandoElenco",
    "ComandoCancellaVariabile",
    "ComandoCancellaTutto",
    "ComandoDisegno",
    "Somma",
    "Differenza",
    "Prodotto",
    "Divisione",
    "Monomio",
    "Num",
    "Seno",
    "Coseno",
    "Tangente",
    "Cotangente",
    "ArcoSeno",
    "ArcoCoseno",
    "ArcoTangente",
    "ArcoCotangente",
    "MonomioNegativo",
    "LogaritmoNaturale",
    "Logaritmo",
    "ValoreAssoluto",
    "Esponenziale",
    "Fattoriale",
    "Variabile",
    "VariabileIndipendente",
  };
}
